import dotenv from 'dotenv';
import jwt from 'jsonwebtoken';
import User from '../models/User.js';
import Department from '../models/Department.js';
import { sendMail } from './email.js';

dotenv.config();

const JWT_SECRET = process.env.JWT_SECRET || 'your-secret-key-change-in-production';
const CLIENT_URL = process.env.CLIENT_URL || 'http://localhost:3000';
const COMPANY_NAME = process.env.COMPANY_NAME || 'Task Manager';
const SUPPORT_EMAIL = process.env.SUPPORT_EMAIL || '';
const HELP_URL = process.env.HELP_URL || '#';
const PRIVACY_URL = process.env.PRIVACY_URL || '#';
const CONTACT_URL = process.env.CONTACT_URL || '#';

/**
 * Initialize default department and user if they don't exist
 * This function runs on server startup
 */
export const initDefaultData = async () => {
  try {
    const defaultUserEmail = process.env.DEFAULT_USER_EMAIL;
    const defaultUserName = process.env.DEFAULT_USER_NAME;
    const defaultDepartmentName = process.env.DEFAULT_DEPARTMENT_NAME;

    // Skip initialization if required env variables are not set
    if (!defaultUserEmail || !defaultUserName || !defaultDepartmentName) {
      console.log('Default user/department configuration not found. Skipping initialization.');
      return;
    }

    // Check if default user exists
    const existingUser = await User.findOne({
      email: defaultUserEmail.toLowerCase(),
      isDeleted: false
    });

    if (existingUser) {
      console.log('Default user already exists. Skipping initialization.');
      return;
    }

    console.log('Default user not found. Initializing default data...');

    // Check if default department exists
    let department = await Department.findOne({
      name: defaultDepartmentName,
      isDeleted: false
    });

    // Create department if it doesn't exist
    if (!department) {
      console.log(`Creating default department: ${defaultDepartmentName}`);
      // Department ID will be automatically generated by the model's pre-save hook
      department = await Department.create({
        name: defaultDepartmentName,
        description: 'Default department for system initialization',
        createdBy: 'system'
      });
      console.log(`Default department created with ID: ${department.departmentId}`);
    } else {
      console.log(`Using existing default department: ${department.name} (${department.departmentId})`);
    }

    // Create default user (without password - user will set it on register page)
    console.log(`Creating default user: ${defaultUserName} (${defaultUserEmail})`);
    const defaultUser = await User.create({
      fullName: defaultUserName,
      email: defaultUserEmail.toLowerCase(),
      departmentId: department.departmentId,
      role: 'admin',
      createdBy: 'system'
    });

    console.log(`Default user created successfully with ID: ${defaultUser.userId}`);
    
    // Send invitation email to default user
    try {
      // Generate JWT invitation token (valid for 7 days)
      const invitationToken = jwt.sign(
        {
          userId: defaultUser.userId,
          email: defaultUser.email,
          type: 'invitation'
        },
        JWT_SECRET,
        { expiresIn: '7d' }
      );
      
      const invitationUrl = `${CLIENT_URL}/register?token=${invitationToken}`;
      
      // Calculate expiry date (7 days from now)
      const expiryDate = new Date();
      expiryDate.setDate(expiryDate.getDate() + 7);
      const formattedExpiryDate = expiryDate.toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
      });
      
      // Send email using new flow with templateId and options
      const mailOptions = {
        inviter_name: 'System Administrator',
        inviter_role: 'admin',
        company_name: COMPANY_NAME,
        user_email: defaultUser.email,
        assigned_role: defaultUser.role,
        department_name: department.name,
        personal_message: 'Welcome! Please set up your account by completing the registration.',
        expiry_date: formattedExpiryDate,
        invitation_url: invitationUrl,
        support_email: SUPPORT_EMAIL,
        help_url: HELP_URL,
        privacy_url: PRIVACY_URL,
        contact_url: CONTACT_URL
      };
      await sendMail(defaultUser.email, 'welcome', mailOptions);

      console.log('Invitation email sent to default user.');
    } catch (emailError) {
      console.error('Error sending invitation email to default user:', emailError);
      // Don't fail initialization if email fails, just log the error
    }
    
    console.log('Default data initialization completed.');
  } catch (error) {
    console.error('Error initializing default data:', error);
    // Don't exit the process, just log the error
    // The server can still run without default data
  }
};
